sonar.projectKey=planning-app
sonar.projectName=planning-app
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=.venv/**,**/__pycache__/**,planning.db,exports/**,tests/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
