"""Deterministic scaffold layer — creates impl/ directory tree + static template files.

No LLM calls here. All writes are idempotent:
- Files whose first line IS the plancraft template header are safe to overwrite.
- Files whose first line is NOT the header are treated as human-edited and skipped
  (unless force=True).
"""
from __future__ import annotations

import json
import re
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from services.scaffold.tech_stack_reader import ScaffoldConfig

# Every generated file must have this as its first line.
_PY_HEADER  = "# generated-by: plancraft-scaffolder"
_JS_HEADER  = "// generated-by: plancraft-scaffolder"
_XML_HEADER = "<!-- generated-by: plancraft-scaffolder -->"

# Marker file that signals scaffold has been completed
SCAFFOLD_MARKER = ".plancraft-scaffold.json"


def _write(path: Path, content: str, force: bool = False) -> None:
    """Write content to path; skip if existing file was NOT generated by plancraft."""
    if path.exists() and not force:
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
        except Exception:
            first_line = ""
        if first_line not in (_PY_HEADER, _JS_HEADER, _XML_HEADER,
                               "# " + _PY_HEADER[2:]):  # toml uses # header
            return  # human-edited — do not overwrite
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_static_tree(
    impl_dir: Path,
    config: "ScaffoldConfig",
    project_name: str,
    force: bool = False,
) -> list[Path]:
    """Create the impl/ directory tree and write static template files.

    Returns the list of Paths that were written.
    """
    written: list[Path] = []
    pkg = config.package_slug

    # Directories
    dirs = [
        impl_dir / "backend" / "src" / pkg,
        impl_dir / "backend" / "tests",
    ]
    if config.has_frontend:
        dirs += [
            impl_dir / "frontend" / "src",
            impl_dir / "frontend" / "tests",
        ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)

    # bootstrap.sh
    lines = [
        "#!/usr/bin/env bash",
        _PY_HEADER,
        "set -euo pipefail",
        "",
        "# Bootstrap the implementation skeleton generated by Plancraft Scaffolder.",
        "# Run once after cloning / unpacking the scaffold archive.",
        "",
        "echo '==> Setting up Python backend...'",
        "cd backend",
        "python3 -m venv .venv",
        ".venv/bin/pip install --upgrade pip -q",
        ".venv/bin/pip install -r requirements.txt -q",
        "git init -q",
        "cd ..",
        "",
    ]
    if config.has_frontend:
        lines += [
            "echo '==> Setting up frontend...'",
            "cd frontend",
            "npm install --silent",
            "cd ..",
            "",
        ]
    lines += [
        "echo ''",
        "echo 'Bootstrap complete!'",
        "echo 'Next: implement the TODO bodies, then run tests.'",
        f"echo '  Backend:  cd backend && .venv/bin/pytest'",
    ]
    if config.has_frontend:
        lines.append("echo '  Frontend: cd frontend && npx vitest run'")

    p = impl_dir / "bootstrap.sh"
    _write(p, "\n".join(lines) + "\n", force=force)
    p.chmod(0o755)
    written.append(p)

    # .gitignore
    _write(impl_dir / ".gitignore", textwrap.dedent(f"""\
        {_PY_HEADER}
        # Python
        __pycache__/
        *.pyc
        .venv/
        *.egg-info/
        dist/
        build/
        .pytest_cache/
        .coverage
        htmlcov/
        # Node
        node_modules/
        .vite/
        *.tsbuildinfo
        # Env
        .env
        .env.local
        # OS
        .DS_Store
        Thumbs.db
    """), force=force)
    written.append(impl_dir / ".gitignore")

    # .env.template
    _write(impl_dir / ".env.template", textwrap.dedent(f"""\
        {_PY_HEADER}
        # Copy to .env and fill in values before running the app.
        DATABASE_URL=sqlite:///./app.db
        SECRET_KEY=change-me-in-production
        DEBUG=true
    """), force=force)
    written.append(impl_dir / ".env.template")

    # impl/README.md
    fe_note = (
        "\n- Run `npm install` for the frontend"
        if config.has_frontend else ""
    )
    fe_test_note = (
        "\n**Frontend (vitest):**\n```bash\ncd frontend && npx vitest run\n```"
        if config.has_frontend else ""
    )
    _write(impl_dir / "README.md", textwrap.dedent(f"""\
        {_PY_HEADER}
        # {project_name} — Implementation Skeleton

        Generated by **Plancraft Scaffolder**.

        ## Quick Start

        ```bash
        bash bootstrap.sh
        ```

        The script will:{fe_note}
        - Create a Python virtualenv and install backend dependencies

        ## Implementing TODOs

        Every method body contains:
        ```python
        raise NotImplementedError("TODO: TASK-NNN")
        ```
        Replace each with your implementation.
        TASK-NNN IDs match Plancraft task IDs.

        ## Running Tests

        **Backend (pytest):**
        ```bash
        cd backend
        .venv/bin/pytest
        ```
        Tests call the stubs and **fail by construction** — red → green → refactor.
        {fe_test_note}
    """), force=force)
    written.append(impl_dir / "README.md")

    # backend/requirements.txt
    _write(impl_dir / "backend" / "requirements.txt", textwrap.dedent(f"""\
        {_PY_HEADER}
        fastapi>=0.111.0
        uvicorn[standard]>=0.29.0
        pydantic>=2.0
        sqlalchemy[asyncio]>=2.0
        aiosqlite>=0.20.0
        python-dotenv>=1.0
        pytest>=8.0
        httpx>=0.27.0
        pytest-asyncio>=0.23.0
    """), force=force)
    written.append(impl_dir / "backend" / "requirements.txt")

    # backend/pyproject.toml
    _write(impl_dir / "backend" / "pyproject.toml", textwrap.dedent(f"""\
        # {_PY_HEADER}
        [build-system]
        requires = ["setuptools>=68", "wheel"]
        build-backend = "setuptools.backends.legacy:build"

        [project]
        name = "{pkg}"
        version = "0.1.0"
        requires-python = ">=3.11"

        [tool.pytest.ini_options]
        testpaths = ["tests"]
        asyncio_mode = "auto"

        [tool.setuptools.packages.find]
        where = ["src"]
    """), force=force)
    written.append(impl_dir / "backend" / "pyproject.toml")

    # backend/src/<pkg>/__init__.py
    _write(
        impl_dir / "backend" / "src" / pkg / "__init__.py",
        f'{_PY_HEADER}\n"""Package: {pkg}."""\n',
        force=force,
    )
    written.append(impl_dir / "backend" / "src" / pkg / "__init__.py")

    # backend/src/<pkg>/main.py
    _write(impl_dir / "backend" / "src" / pkg / "main.py", textwrap.dedent(f"""\
        {_PY_HEADER}
        \"\"\"FastAPI application entry point for {project_name}.\"\"\"
        from fastapi import FastAPI

        app = FastAPI(title="{project_name}")


        @app.get("/health")
        async def health() -> dict:
            return {{"status": "ok"}}
    """), force=force)
    written.append(impl_dir / "backend" / "src" / pkg / "main.py")

    # backend/tests/conftest.py
    _write(impl_dir / "backend" / "tests" / "conftest.py", textwrap.dedent(f"""\
        {_PY_HEADER}
        \"\"\"Pytest configuration and shared fixtures for {project_name}.\"\"\"
        import pytest
        from httpx import AsyncClient, ASGITransport

        from {pkg}.main import app


        @pytest.fixture
        async def client():
            async with AsyncClient(
                transport=ASGITransport(app=app),
                base_url="http://test",
            ) as c:
                yield c
    """), force=force)
    written.append(impl_dir / "backend" / "tests" / "conftest.py")

    # Frontend (only when has_frontend)
    if config.has_frontend:
        _write(impl_dir / "frontend" / "package.json", json.dumps({
            "name": f"{pkg}-frontend",
            "version": "0.1.0",
            "private": True,
            "scripts": {
                "dev": "vite",
                "build": "tsc && vite build",
                "test": "vitest run",
            },
            "dependencies": {
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
            },
            "devDependencies": {
                "@types/react": "^18.2.0",
                "@types/react-dom": "^18.2.0",
                "@vitejs/plugin-react": "^4.2.0",
                "typescript": "^5.3.0",
                "vite": "^5.2.0",
                "vitest": "^1.4.0",
                "@testing-library/react": "^15.0.0",
                "@testing-library/jest-dom": "^6.4.0",
                "jsdom": "^24.0.0",
            },
        }, indent=2), force=force)
        written.append(impl_dir / "frontend" / "package.json")

        _write(impl_dir / "frontend" / "tsconfig.json", json.dumps({
            "compilerOptions": {
                "target": "ES2020",
                "lib": ["ES2020", "DOM"],
                "module": "ESNext",
                "moduleResolution": "bundler",
                "jsx": "react-jsx",
                "strict": True,
                "skipLibCheck": True,
                "outDir": "dist",
            },
            "include": ["src", "tests"],
        }, indent=2), force=force)
        written.append(impl_dir / "frontend" / "tsconfig.json")

        _write(impl_dir / "frontend" / "vite.config.ts", textwrap.dedent(f"""\
            {_JS_HEADER}
            import {{ defineConfig }} from 'vite';
            import react from '@vitejs/plugin-react';

            export default defineConfig({{
              plugins: [react()],
              test: {{
                environment: 'jsdom',
                globals: true,
              }},
            }});
        """), force=force)
        written.append(impl_dir / "frontend" / "vite.config.ts")

        _write(impl_dir / "frontend" / "index.html", textwrap.dedent(f"""\
            <!DOCTYPE html>
            {_XML_HEADER}
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>{project_name}</title>
              </head>
              <body>
                <div id="root"></div>
                <script type="module" src="/src/main.tsx"></script>
              </body>
            </html>
        """), force=force)
        written.append(impl_dir / "frontend" / "index.html")

        _write(impl_dir / "frontend" / "src" / "main.tsx", textwrap.dedent(f"""\
            {_JS_HEADER}
            import React from 'react';
            import ReactDOM from 'react-dom/client';

            function App() {{
              return <div>{project_name}</div>;
            }}

            ReactDOM.createRoot(document.getElementById('root')!).render(
              <React.StrictMode>
                <App />
              </React.StrictMode>
            );
        """), force=force)
        written.append(impl_dir / "frontend" / "src" / "main.tsx")

    # Scaffold marker
    marker_path = impl_dir / SCAFFOLD_MARKER
    marker_path.write_text(json.dumps({
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "plancraft-scaffolder",
        "has_frontend": config.has_frontend,
        "package_slug": pkg,
    }, indent=2), encoding="utf-8")
    written.append(marker_path)

    return written
