"""README renderer — writes the workspace root README.md with full ToC and cross-links."""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from services.export.queries import Arc42ExportData
    from services.workspace.workspace import ProjectWorkspace


_ARC42_SECTIONS = [
    (1, "introduction", "Introduction and Goals"),
    (2, "constraints", "Constraints"),
    (3, "context", "System Context"),
    (4, "solution_strategy", "Solution Strategy"),
    (5, "building_blocks", "Building Blocks"),
    (6, "runtime", "Runtime View"),
    (7, "deployment", "Deployment View"),
    (8, "crosscutting", "Cross-cutting Concepts"),
    (9, "decisions", "Architecture Decisions"),
    (10, "quality", "Quality Requirements"),
    (11, "risks", "Risks and Technical Debt"),
    (12, "glossary", "Glossary"),
]


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def render_readme(ws: "ProjectWorkspace", data: "Arc42ExportData") -> Path:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    arc42_rows = "\n".join(
        f"| {n:02d} | [{title}](docs/arc42/{n:02d}_{name}.md) |"
        for n, name, title in _ARC42_SECTIONS
    )

    adr_rows_parts: list[str] = []
    for n, dec in enumerate(data.decisions, start=1):
        slug = _slug(dec.title)
        adr_rows_parts.append(
            f"| ADR-{n:04d} | [{dec.title}](docs/adr/{n:04d}-{slug}.md) |"
        )
    adr_rows = "\n".join(adr_rows_parts) if adr_rows_parts else "| – | *No decisions recorded yet.* |"

    story_rows_parts: list[str] = []
    for n, story in enumerate(data.stories, start=1):
        story_rows_parts.append(
            f"| US-{n:03d} | {story.priority or 'should'} | As a {story.as_a}, I want {story.i_want} | [link](docs/stories/US-{n:03d}.md) |"
        )
    story_rows = "\n".join(story_rows_parts) if story_rows_parts else "| – | – | *No stories recorded yet.* | – |"

    spec_count = len(data.specs)
    task_count = len(data.tasks)

    content = f"""# {data.project_name}

*Generated by Plancraft — {now}*

---

## Architecture Documentation (arc42)

| # | Section |
|---|---------|
{arc42_rows}

> C4 model: [docs/c4/workspace.dsl](docs/c4/workspace.dsl)

---

## Architecture Decision Records

| ID | Title |
|----|-------|
{adr_rows}

---

## User Stories

| ID | Priority | Summary | File |
|----|----------|---------|------|
{story_rows}

---

## Test Specifications

{spec_count} spec(s) defined → [tests/specs/](tests/specs/)

---

## Tasks

{task_count} task(s) → [tasks/tasks.json](tasks/tasks.json) · [tasks/](tasks/)

---

*This documentation is generated as code. All files are kept in sync with the planning database.*
"""
    path = ws.readme
    path.write_text(content, encoding="utf-8")
    return path
