"""Impl export target — zips the impl/ code skeleton."""
from __future__ import annotations

import shutil
from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession

from .base import BuildResult


class ImplTarget:
    name = "impl"
    display_name = "Implementation Skeleton"
    description = (
        "Zips the impl/ directory (implementation-ready code skeleton) "
        "produced by the Scaffolder phase."
    )

    async def build(self, project_id: str, out_dir: Path, db: AsyncSession) -> BuildResult:
        from services.export.queries import ExportDataLoader
        from services.scaffold.tree_builder import SCAFFOLD_MARKER

        loader = ExportDataLoader(db)
        project = await loader.get_project(project_id)

        if not project.root_path:
            raise ValueError("Project workspace not initialised yet.")

        impl_dir = Path(project.root_path) / "impl"
        if not impl_dir.exists():
            raise ValueError(
                "impl/ directory does not exist. "
                "Run POST /projects/{id}/scaffold first."
            )
        if not (impl_dir / SCAFFOLD_MARKER).exists():
            raise ValueError(
                "impl/ was not generated by Plancraft Scaffolder "
                "(missing .plancraft-scaffold.json marker)."
            )

        result = BuildResult(out_dir=out_dir)
        for src in impl_dir.rglob("*"):
            if not src.is_file():
                continue
            rel = src.relative_to(impl_dir)
            dest = out_dir / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            result.add_file(dest)

        return result
