"""Scaffold router.

POST /projects/{project_id}/scaffold    - trigger scaffolding (SSE stream)
GET  /projects/{project_id}/scaffold/status - query current scaffold state
"""
from __future__ import annotations

import json
import logging
import re

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from database import AsyncSessionLocal, get_db
from models.db import Project, RoleExecutionTrace
from services.knowledge.common import KnowledgeBase
from services.scaffold.tech_stack_reader import read_scaffold_config
from services.scaffold.tree_builder import SCAFFOLD_MARKER, build_static_tree
from services.scaffold.llm import run_scaffolder_llm

log = logging.getLogger(__name__)
router = APIRouter()

_SLUG_RE = re.compile(r"[^a-z0-9]+")
_PY_HEADER = "# generated-by: plancraft-scaffolder"
_JS_HEADER = "// generated-by: plancraft-scaffolder"


class ScaffoldRequest(BaseModel):
    force: bool = False


def _sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data)}\n\n"


async def _review_has_run(project_id: str, db: AsyncSession) -> bool:
    r = await db.execute(
        select(RoleExecutionTrace)
        .where(
            RoleExecutionTrace.project_id == project_id,
            RoleExecutionTrace.role == "review",
            RoleExecutionTrace.final.is_(True),
        )
        .limit(1)
    )
    return r.scalar_one_or_none() is not None


def _has_non_generated_changes(impl_dir) -> bool:
    """Return True if impl/ contains files not generated by plancraft."""
    from pathlib import Path
    impl_dir = Path(impl_dir)
    for suffix in ("*.py", "*.ts", "*.tsx"):
        for f in impl_dir.rglob(suffix):
            try:
                first = f.read_text(encoding="utf-8", errors="replace").splitlines()[0]
                if first not in (_PY_HEADER, _JS_HEADER):
                    return True
            except Exception:
                pass
    return False


@router.post("/projects/{project_id}/scaffold")
async def scaffold_project(
    project_id: str,
    body: ScaffoldRequest,
    db: AsyncSession = Depends(get_db),
):
    """Trigger the Scaffolder phase for a project (SSE stream)."""
    kb = KnowledgeBase(db)
    try:
        project = await kb.get_project(project_id)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc))

    if not project.root_path:
        raise HTTPException(status_code=422, detail="Project workspace not initialised yet.")

    if not body.force and not await _review_has_run(project_id, db):
        raise HTTPException(
            status_code=422,
            detail=(
                "Scaffolder requires the Reviewer phase to have run at least once. "
                "Run POST /projects/{project_id}/review/full first, "
                "or pass force=true to bypass (dev/test only)."
            ),
        )

    from pathlib import Path
    impl_dir = Path(project.root_path) / "impl"

    if not body.force and impl_dir.exists() and (impl_dir / SCAFFOLD_MARKER).exists():
        if _has_non_generated_changes(impl_dir):
            raise HTTPException(
                status_code=409,
                detail=(
                    "impl/ contains non-generated files. "
                    "Pass force=true to regenerate (overwrites template files only, "
                    "leaves human-edited files untouched)."
                ),
            )

    async def event_stream():
        async with AsyncSessionLocal() as stream_db:
            try:
                pkg_slug = _SLUG_RE.sub("_", project.name.lower()).strip("_") or "app"

                config = await read_scaffold_config(project_id, stream_db, package_slug=pkg_slug)
                yield _sse("scaffold_progress", {
                    "message": f"Config: has_frontend={config.has_frontend}, package_slug={pkg_slug}"
                })

                # Layer 1: deterministic tree
                static_paths = build_static_tree(impl_dir, config, project.name, force=body.force)
                yield _sse("scaffold_progress", {
                    "message": f"Static tree: {len(static_paths)} file(s) written"
                })

                # Layer 2: LLM-generated modules
                llm_file_count = 0
                async for event in run_scaffolder_llm(project_id, stream_db, impl_dir, config):
                    yield _sse(event["type"], event)
                    if event["type"] == "file_written":
                        llm_file_count += 1

                total = len(static_paths) + llm_file_count
                yield _sse("done", {
                    "files_written": total,
                    "impl_dir": str(impl_dir),
                    "has_frontend": config.has_frontend,
                })

            except Exception as exc:
                log.error("Scaffold failed for project %s: %s", project_id, exc, exc_info=True)
                yield _sse("error", {"message": str(exc)})

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@router.get("/projects/{project_id}/scaffold/status")
async def scaffold_status(
    project_id: str,
    db: AsyncSession = Depends(get_db),
):
    """Return the current scaffold status for a project."""
    kb = KnowledgeBase(db)
    try:
        project = await kb.get_project(project_id)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc))

    review_ran = await _review_has_run(project_id, db)

    if not project.root_path:
        return JSONResponse({
            "scaffold_complete": False,
            "impl_exists": False,
            "review_has_run": review_ran,
            "reason": "workspace_not_initialised",
        })

    from pathlib import Path
    impl_dir = Path(project.root_path) / "impl"
    marker_path = impl_dir / SCAFFOLD_MARKER
    scaffold_done = marker_path.exists()

    marker_data: dict = {}
    if scaffold_done:
        try:
            marker_data = json.loads(marker_path.read_text())
        except Exception:
            pass

    return JSONResponse({
        "scaffold_complete": scaffold_done,
        "impl_exists": impl_dir.exists(),
        "review_has_run": review_ran,
        "impl_dir": str(impl_dir) if impl_dir.exists() else None,
        "marker": marker_data,
        "has_non_generated_changes": (
            _has_non_generated_changes(impl_dir) if scaffold_done else False
        ),
    })
